# Generated by Django 5.2.5 on 2025-08-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_email_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
